# Generated by Django 3.2.6 on 2021-09-13 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_list_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users_list',
        ),
    ]
